ch:
  # name
  - "ch"
  # arrival
  - [2, 3]
  # running
  - [2, 5]
  # capacity
  - 3
  # workers
  - 2
p:
  # name
  - "p"
  # arrival
  - [2, 5]
  # running
  - [3, 5]
  # capacity
  - 3
  # workers
  - 1
start_time: 2.5
iterations: 100000
reps: 5
