iterations: 100000
reps: 1

queues:
  f1:
    arrival: [1,4]
    workers: 1
    run: [1,1.5]
    next_idx: 
      f2: 0.8
      f3: 0.2
  f2:
    workers: 3
    capacity: 5
    run: [5,10]
    next_idx: 
      f1: 0.3
      f3: 0.5
  f3:
    workers: 2
    capacity: 8
    run: [10,20]
    next_idx: 
      f2: 0.7

first_proc: 1