iterations: 1000000
reps: 5

queues:
  q1:
    capacity: 3
    workers: 2
    run: [2,5]
    # Optionals
    arrival: [2,3]
    next_idx: q2
    start: True
  q2:
    capacity: 3
    workers: 1
    run: [3,5]

first_proc:
  time: 2.5